# Generated by Django 3.1.7 on 2021-02-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionComerciosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalidadesForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=200)),
            ],
        ),
    ]
