# Generated by Django 3.1.7 on 2021-02-27 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionComerciosApp', '0003_postdecomerciosforms_localidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComercioForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comercio', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='postdecomerciosforms',
            old_name='nombre_comercio',
            new_name='nombre_del_comercio',
        ),
        migrations.AddField(
            model_name='postdecomerciosforms',
            name='tipo_comercio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionComerciosApp.comercioforms'),
            preserve_default=False,
        ),
    ]
