# Generated by Django 3.1.7 on 2021-02-28 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionComerciosApp', '0004_auto_20210227_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('img_producto', models.ImageField(upload_to='productos-comercio')),
                ('comercio_pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionComerciosApp.postdecomerciosforms')),
            ],
        ),
    ]
