# Generated by Django 3.1.7 on 2021-03-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionComerciosApp', '0006_auto_20210305_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosforms',
            name='categroia_pruductos',
        ),
        migrations.AddField(
            model_name='categoriaproductos',
            name='add_producots',
            field=models.ManyToManyField(to='GestionComerciosApp.ProductosForms'),
        ),
    ]
