# Generated by Django 3.1.7 on 2021-03-07 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionComerciosApp', '0011_remove_comercioforms_comercio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaproductos',
            name='add_producots',
        ),
        migrations.AlterField(
            model_name='categoriaproductos',
            name='pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionComerciosApp.productosforms'),
        ),
    ]
