# Generated by Django 3.1.7 on 2021-03-07 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GestionComerciosApp', '0012_auto_20210307_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaproductos',
            name='pertenece',
        ),
        migrations.AddField(
            model_name='categoriaproductos',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productosforms',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionComerciosApp.categoriaproductos'),
        ),
    ]
